import { Feather } from '@expo/vector-icons'
import { useUser } from '@clerk/expo'
import * as Contacts from 'expo-contacts'
import { Stack, useFocusEffect, useRouter } from 'expo-router'
import { useCallback, useState } from 'react'
import { ActivityIndicator, Pressable, StyleSheet, Switch, Text, View } from 'react-native'

import { getProfile, savePreferences, syncLinkedContacts } from '../src/api/client'
import { useAuthHeaders } from '../src/auth/useAuthToken'
import { ProductScreen, ScreenHeader } from '../src/components/ProductUI'
import { OnboardingPreferences } from '../src/types'
import { colors, radii } from '../src/ui/theme'

export default function NotificationSettings() {
  const router = useRouter(); const { user } = useUser(); const { getAuthHeaders } = useAuthHeaders(); const [profile, setProfile] = useState<OnboardingPreferences | null>(null); const [enabled, setEnabled] = useState(true); const [loading, setLoading] = useState(true); const [saving, setSaving] = useState(false); const [linking, setLinking] = useState(false); const [linked, setLinked] = useState(false); const [error, setError] = useState<string | null>(null)
  const load = useCallback(async () => { setLoading(true); setError(null); try { const next = await getProfile(await getAuthHeaders()); setProfile(next); setEnabled(next.onboarding_data?.notifications !== false) } catch (reason) { setError(message(reason, 'Unable to load notification settings.')) } finally { setLoading(false) } }, [getAuthHeaders])
  useFocusEffect(useCallback(() => { void load() }, [load]))
  const save = async () => { if (!profile?.onboarding_data) return setError('Your saved profile is incomplete. Please try again.'); setSaving(true); setError(null); try { await savePreferences({ ...profile, onboarding_data: { ...profile.onboarding_data, notifications: enabled } }, await getAuthHeaders()); router.back() } catch (reason) { setError(message(reason, 'Unable to save notification settings.')) } finally { setSaving(false) } }
  const linkContacts = async () => { setLinking(true); setError(null); try { const permission = await Contacts.requestPermissionsAsync(); if (permission.status !== 'granted') throw new Error('Contacts permission is needed to find friends who join Fairway.'); const result = await Contacts.getContactsAsync({ fields: [Contacts.Fields.Emails, Contacts.Fields.PhoneNumbers] }); const contacts = result.data.flatMap((contact) => [...(contact.emails?.map((item) => item.email) ?? []), ...(contact.phoneNumbers?.map((item) => item.number) ?? [])]).filter((value): value is string => Boolean(value)); const account = [...(user?.emailAddresses.map((item) => item.emailAddress) ?? []), ...(user?.phoneNumbers.map((item) => item.phoneNumber) ?? [])]; await syncLinkedContacts({ account_identifiers: account, contact_identifiers: contacts }, await getAuthHeaders()); setLinked(true) } catch (reason) { setError(message(reason, 'Unable to link contacts.')) } finally { setLinking(false) } }
  return <><Stack.Screen options={{ headerShown: false }} /><ProductScreen><ScreenHeader title="Notification settings" onBack={() => router.back()} />{loading ? <ActivityIndicator accessibilityLabel="Loading notification settings" color={colors.pine} /> : <><View style={styles.heroIcon}><Feather name="bell" size={26} color={colors.pine} /></View><View style={styles.intro}><Text style={styles.introTitle}>Stay in the loop</Text><Text style={styles.introBody}>Control whether GolfRank can notify you about relevant activity and updates.</Text></View><View style={styles.group}><View style={styles.row}><View style={styles.rowCopy}><Text style={styles.rowTitle}>Allow notifications</Text><Text style={styles.rowBody}>{enabled ? 'Notifications are enabled for your account.' : 'You will not receive GolfRank notifications.'}</Text></View><Switch accessibilityLabel="Allow notifications" onValueChange={setEnabled} trackColor={{ false: '#D4D7D4', true: colors.pineSoft }} thumbColor={enabled ? colors.pine : '#FFFFFF'} value={enabled} /></View><Pressable accessibilityRole="button" disabled={linking} onPress={() => void linkContacts()} style={styles.contactRow}><View style={styles.rowCopy}><Text style={styles.rowTitle}>Link contacts</Text><Text style={styles.rowBody}>{linked ? 'Contacts linked. We’ll let you know when someone joins.' : 'Get a notification when someone from your contacts joins Fairway.'}</Text></View>{linking ? <ActivityIndicator color={colors.pine} /> : <Feather name={linked ? 'check' : 'users'} size={19} color={colors.pine} />}</Pressable></View><Text style={styles.note}>Contact identifiers are hashed before storage. Device-level notification permission is managed in iOS Settings.</Text>{error ? <Text accessibilityRole="alert" style={styles.error}>{error}</Text> : null}<Pressable accessibilityRole="button" disabled={saving} onPress={() => void save()} style={[styles.saveButton, saving && styles.disabled]}>{saving ? <ActivityIndicator color="#FFFFFF" /> : <Text style={styles.saveText}>Save changes</Text>}</Pressable></>}</ProductScreen></>
}
function message(reason: unknown, fallback: string) { return reason instanceof Error ? reason.message : fallback }
const styles = StyleSheet.create({ heroIcon: { alignItems: 'center', alignSelf: 'center', backgroundColor: colors.pineSoft, borderRadius: 29, height: 58, justifyContent: 'center', marginTop: 8, width: 58 }, intro: { alignItems: 'center', gap: 7, paddingHorizontal: 24 }, introTitle: { color: colors.ink, fontFamily: 'Georgia', fontSize: 22 }, introBody: { color: colors.muted, fontSize: 12, lineHeight: 18, textAlign: 'center' }, group: { backgroundColor: colors.card, borderColor: colors.line, borderRadius: radii.small, borderWidth: 1 }, row: { alignItems: 'center', flexDirection: 'row', gap: 15, minHeight: 76, paddingHorizontal: 15, paddingVertical: 12 }, contactRow: { alignItems: 'center', borderTopColor: colors.line, borderTopWidth: StyleSheet.hairlineWidth, flexDirection: 'row', gap: 15, minHeight: 68, paddingHorizontal: 15, paddingVertical: 10 }, rowCopy: { flex: 1, gap: 5 }, rowTitle: { color: colors.ink, fontFamily: 'Georgia', fontSize: 15 }, rowBody: { color: colors.muted, fontSize: 10, lineHeight: 14 }, note: { color: colors.muted, fontSize: 10, lineHeight: 15, paddingHorizontal: 4 }, error: { color: colors.error, fontSize: 11, lineHeight: 16, textAlign: 'center' }, saveButton: { alignItems: 'center', backgroundColor: colors.pine, borderRadius: radii.pill, justifyContent: 'center', minHeight: 50, marginTop: 'auto' }, saveText: { color: '#FFFFFF', fontSize: 14, fontWeight: '800' }, disabled: { opacity: 0.55 } })
